accelerator: null
accumulate_grad_batches: null
amp_backend: native
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
avg_reward_len: 100
batch_size: 64
benchmark: null
check_val_every_n_epoch: 1
critic_beta: 0.5
default_root_dir: null
detect_anomaly: false
deterministic: null
devices: null
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
entropy_beta: 0.01
env: WordleEnv100-v0
epoch_len: 10
fast_dev_run: false
gamma: 0.99
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: null
hidden_size: 256
ipus: null
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
log_every_n_steps: 50
logger: true
lr: 0.0001
max_epochs: null
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
n_hidden: 1
network_name: SumChars
num_nodes: 1
num_processes: null
num_sanity_val_steps: 2
overfit_batches: 0.0
plugins: null
precision: 32
prob_cheat: 0
prob_play_lost_word: 0
profiler: null
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
replay_size: 1000
resume_from_checkpoint: lightning_logs/version_10/checkpoints/epoch=0-step=283700.ckpt
seed: 123
strategy: null
sync_batchnorm: false
tpu_cores: null
track_grad_norm: -1
val_check_interval: null
weight_decay: 0.0
weights_save_path: null
